familymoments/family-moments-BE

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostUserReq.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostUserRes.java
- family-moments/src/main/java/com/spring/familymoments/utils/ValidationRegex.java
- family-moments/src/test/java/com/spring/familymoments/UserControllerTest.java
1. User. java
-  User entity birthdate 칼럼 LocalDate에서 String 자료형으로 변경했습니다. 
-  length는 10으로 잡았습니다.
2. BaseResponseStatus.java
- 예외 처리 코드 추가했습니다.
- 작업 내역 
1. familymoments/config/BaseResponseStatus.java
2. familymoments/domain/user/UserController.java
4. familymoments/domain/user/UserRepository.java
5. familymoments/domain/user/UserService.java
6. familymoments/domain/entity/User.java
7. familymoments/domain/model/PostUserReq.java
8. familymoments/domain/model/PostUserRes.java
9. familymoments/utils/ValidationRegex.java
10. familymoments/UserControllerTest.java
- 동작
- > 사용자가 회원가입 폼 요소들 중 아이디를 입력하지 않았을 때, 관련 동작 화면 
- 특이 사항
- 이후에 벤티님이 봐주실 예정입니다.
close: #1
- PostUserRes에 패스워드의 값을 return 해서 보안 상 좋지 않고 
- 이후에 로그인 구현할 때 다시 수정할 부분입니다. 
- 벤티 님이 <jwt 작업> 함께 도와주실 예정입니다.
> feat : 회원가입 api 생성

- .idea/modules.xml
- family-moments/src/main/java/com/spring/familymoments/config/BaseResponse.java
- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/common/entity/UserFamily.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/model/FamilyDto.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyRes.java
- familyId로 가족정보 조회
- 초대 코드로 가족 정보 조회
- 가족 초대 api
- 초대 승락 api
- 동작 
- 특이 사항
close: #8
controller의 createFamily 부분 주석처리하고 작업했습니다!
> feat: 가족정보 조회 / 가족 초대 및 승락 api

- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- 이유
- 아이디 중복확인
- `userRepository`에 아이디 존재 여부를 확인하는 `boolean` 형 JPA 메소드 추가
- 이미 가입한 아이디가 존재하면 **true** 출력, 가입한 아이디가 없으면 **false** 출력
- 이메일 중복확인도 크게 다를 것 같지 않아서, 비슷한 방법으로 구현할 예정입니다!
close: #
- `createUser`의 인자로 결과값을 넘겨주도록 구현했습니다!
> feat: 아이디 중복확인 api

- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- 이유
- 아이디 중복확인
- `userRepository`에 이메일 존재 여부를 확인하는 `boolean` 형 JPA 메소드 추가
- 이미 가입한 이메일이 존재하면 **true** 출력, 가입한 이메일이 없으면 **false** 출력
close: #
- `createUser`의 인자로 결과값을 넘겨주도록 구현했습니다!
> feat: 이메일 중복확인 api

- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentWithUserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostWithLoveRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostWithUserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveController.java
- family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveService.java
- family-moments/src/main/java/com/spring/familymoments/domain/postLove/model/PostLoveReq.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- 코드에 남아있는 `writerId`를 `writer`로 수정
- 게시글 좋아요 생성 및 삭제
- **게시글 좋아요 생성**
- **게시글 좋아요 삭제**
**예외처리**는 2가지 경우에 대해서 처리했습니다.
1. 이미 좋아요를 누른 게시글에 다시 좋아요를 누르려고 하는 경우
2. 좋아요를 누르지 않은 게시글의 좋아요를 취소하려는 경우
- 시간이 없어서 게시글 좋아요 생성 및 삭제를 같은 브랜치에 만들었습니다!
close: #
- 일단 오류를 수정하느라 급하게 PR를 반영했는데, 요청하신대로 처리가 되었는지 꼭 확인 부탁드립니다! ㅠㅠ (@zzo3ozz)
- url과 관련하여 현재 양쪽 모두 `@RequestParam`으로 `postId`를 넘겨주는 상태인데, 확인 부탁드립니다!
> feat: 게시글 좋아요 생성 및 삭제

- family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveController.java
- 인자로 넘겨주는 값이 중복되어 하나를 삭제하였습니다.
-  `PostLoveController`의 `@RequestBody` 삭제 
- **게시글 좋아요 생성**
- **게시글 좋아요 삭제**
**예외처리**는 2가지 경우에 대해서 처리했습니다.
1. 이미 좋아요를 누른 게시글에 다시 좋아요를 누르려고 하는 경우
2. 좋아요를 누르지 않은 게시글의 좋아요를 취소하려는 경우
close: #
- 요청하신대로 반영했습니다! (@zzo3ozz)
> fix: 게시글 좋아요 생성 및 삭제

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- 특정 일 기준 최신 post 조회 (10건)
- 특정 일 기준 기준 postId 이후 post 조회 (10건)
- 특정 일 기준 최신 post 목록 
- 특정 일, postId 기준 이후 post 목록
> feat: 특정 일 기준 post 목록 조회

- .idea/compiler.xml
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- 특정 월의 post가 존재하는 날짜 리스트를 조회합니다. 중복값은 제외되며 오름차순으로 정렬됩니다.
- 동작
> feat: 특정 월 post가 존재하는 날짜 조회

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/MultiPostRes.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/SinglePostRes.java
post 정보 response 시 LocalDateTime이 아닌 LocalDate로 전송하도록 변경
- API 설계 시 time 정보를 제외하고 보내는 것으로 기획되었으나, Time 정보가 포함되어 전송되고 있었습니다.
서버 내에서 정렬된 상태로 데이터를 전송하므로, 시간 정보를 제외해도 프론트에서 문제가 발생하지 않습니다.
> feat: post 도메인 response 수정(LocalDateTime -> LocalDate)

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java
- 쿼리 중 누락된'status = ACTIVE' 구문을 추가하였습니다.
> fix: getOnePost 시 delete 된 post 가 출력되는 문제 수정

- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- 아이디/이메일 중복확인의 Method를 `GetMapping`에서 `PostMapping`으로 수정
- `Controller`의 인자가 `RequestParam`에서 `RequestBody`로 수정되었었음(#50)
- 아이디/이메일 중복확인의 Method를 `GetMapping`에서 `PostMapping`으로 수정
close: #
> fix: 아이디/이메일 중복확인의 Method를 PostMapping으로 수정

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- 비밀번호 재설정(로그인 없이 진행) 관련 `Service`의 `.orElseThrow()` 코드 
- 이유: 예외처리 형식을 맞추기 위해서 수정했습니다.
- 비밀번호 재설정(로그인 없이 진행) 관련 `Service`의 `.orElseThrow()` 코드 
- 명세서에 작성했습니다.
- #37, #40, #41
- `InternalServerException`을 없애고, `Controller`에 `try-catch`를 추가했다는 점에서 위 PR들과 비슷합니다.
close: #
> fix: InternalServerException 삭제

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveService.java
- FE의 브이엘이 요청한 앨범의 상세 페이지 조회 api를 추가하였습니다.
postId를 통해 이미지 리스트를 return하는 api입니다. 
- 요청서 (https://www.notion.so/API-c5442a4f509f497582f2c49c93499631?pvs=4)
- API Sheet (https://www.notion.so/55a0f64db5fa475fad23b0812c7ddd00?pvs=4)
- BaseResponseStatus 중 minnie_POSTS_INVAIED_…를 minnie_POSTS_INVALID_…로 변경하였습니다.
- 동작
> feat: 앨범의 상세 페이지 api

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/Post.java
- image 수정 시 이미지 개수가 늘거나(out of index error), 줄어들 때 (반영 안 됨) 이슈가 있었습니다.
- 추가로, Post Entity의 구문 에러로 img1의 url만 갱신되던 문제가 있었습니다.
- 차후 프론트엔드에서의 form-data patch 사용 불가 연락 시 변동될 수 있습니다.
> fix : image 수 변동 시 out of index 에러 수정, img1만 갱신되던 에러 수정

- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/model/PatchPwdReq.java
1. 회원정보수정API (Patch 관련 API) - 프론트분과 계속 소통하며 로그를 확인하다가 RequestPart가 Missing 된다는 것을 확인했다. 그 이후에 내 코드를 자세히 살펴보니... RequestPart가 아닌 RequestParam으로 오타가 나있는 것을 확인했다.  (postman은 왜 괜찮았는지 의문)
2. 비밀번호 변경 예외처리 
2-1. 새비밀번호 재확인 예외처리를 추가했다.
2-2. 프론트 요청을 받아 원래 **400번으로** 통일되었던 에러 코드 번호를 **4000~4004로** 분리해서 새로 설정했다. 관련 문서를 찾 
아본 결과 프론트와 원활한 소통을 위해서 Custom한 Error Code가 필요하다는 사실을 확인해서 아래와 같이 변경했다.
close: #74
- 에러 코드 번호를 임의로 4000~4004로 설정했는데 이 부분에 관해 어떻게 생각하시는 지 의견 듣고 싶습니다!
> Fix : 회원정보수정, 비밀번호변경 API 오타 및 예외처리 수정 

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- form-data 사용 시 PATCH method에서 오류 확인. PATCH → POST method변경
- 비밀번호 인증 API를 GET method → POST method 변경
- Post 수정 결과 return 시 img array 중 의도하지 않은 null 리턴 이슈 수정
- User 도메인 중 비밀번호 인증 API가 requestbody를 요청하나, GET으로 설계되어 있어 이를 POST로 수정하였습니다. (@spacewalk00)
- Postman 등 API 테스트 툴에서는 문제가 되지 않았으나,
프론트 연동 시 Patch method에 form-data 사용하는 경우(User domain 및 Post domain) 에러가 발생하는 이슈가 있었습니다. 
일차적으로 image/png, application/json을 각각 Content-type으로 받는 API 2개로 분리를 고려하였으나,
데모데이까지의 시간(프론트에서의 작업 변겅)을 고려하여 POST로 Method를 변경했습니다.
- 해당 과정 중 User API의 경우 RequestPart 중 일부가 name 지정이 누락되어 에러가 발생, name을 명시하였습니다. (UserController, 312 Line)
- Post 수정 결과 return 시 img array 배열이 ["url1", "url2", null, null] 등으로 return 되는 것을 확인,
치명적인 이슈는 아니지만 의도했던 결과가 아니기에 수정하였습니다.
@spacewalk00 User 부분 더블체크 부탁드립니다!
> fix : PATCH to POST

- family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java
- 회원 정보 수정시 이름만 수정이 안됐습니다. 
- 그 원인이었던 User entity name 칼럼 옵션 updatable=false를 지웠습니다!
회원 정보 수정 api 실행 후 회원정보 조회 api 실행 시 결과 화면입니다! (== 이름이 잘 수정이 된다) 
- entity 내용 수정이더라도 jpa 관련 내용이기 때문에 db를 갱신할 필요가 없습니다!
close: #91
> Fix : Feature/user edit - name updatable

- family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/AuthController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/AuthService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostLoginRes.java
- userfamily 테이블에서 가장 오래 전에 생성됐던 하나의 튜플에서  status가 active인 userfamily의 familyId를 추출해냅니다!
- 가입한 family가 없을 경우, null을 반환합니다!
1. 구현 특이사항
- db 안에 여러 가족들이 존재하는 것을 고려해서 구현했습니다! 
- 데모데이 때는 db 안에 family가 한 가족만 존재할 수 있게 db 안 데이터 정리가 필요합니다!
2. commit 특이사항 - **"로그인 api -familyId 추가" 관련 커밋 확인해주시면 됩니다!! (위에서 3번째 commit)**
- 오류가 없는 줄 알고 pull request를 이전에 한번 보냈다가 오류가 존재해서 닫았습니다.!
- commit을 돌렸음에도 원격 레포지토리에 관련 내용이 이미 담겨져 있는데 pull를 하는 바람에
- 이전 내용이 commit에 포함되어있습니다! 😂 참고해주세요!
close: #61
> Fix : login api - familyId 반환 추가

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java
> fix : order by 기준을 postID에서 createdAt 으로 변경

- family-moments/build.gradle
- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/AlbumRes.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/MultiPostRes.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/PostInfoReq.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/SinglePostRes.java
- Swagger document 세팅
- `Controller`, `DTO` 설명 및 예시 작성
- Validation Check를 위해 사용하는 `User`가 docs에 노출되는 문제의 경우, 
@Parameter(hidden = true) annotation을 사용해 숨김 처리
- Error refactoring
- AuthIncepter 도입에 따른 Controller단의 중복 val 과정 삭제
- Service단의 `throw BaseException` 구문 삭제
- createPost 시 error case 추가
- 유저가 해당 가족의 멤버인지를 확인하는 validation 구문 추가
- post 생성에 실패한 경우 error 추가
> Feat : [post] - swagger setting, Error Handler

- family-moments/src/main/java/com/spring/familymoments/domain/user/EmailController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostUserReq.java
- 회원 가입 API에서 비밀번호 입력 폼을 2개에서 1개로 수정
- 회원 가입 API에서 비밀번호 입력 폼을 2개에서 1개로 수정 
- `isEmpty()`가 적용되지 않은 API들이 있어서 전부 수정했습니다.
- `throw`관련 코드 정리는 다음 PR에 적용하겠습니다!
close: #
> Fix: 회원 가입 API 수정

- family-moments/src/main/java/com/spring/familymoments/config/advice/ExceptionAdvice.java
- spring MVC Exception의 경우, ExceptionAdvice가 ResponseEntityExceptionHandler을 상속받으면 reponse body가 빈 값으로 반환된다. request에 빠진 값이 있는 경우 MissingServletRequestPartException가 발생하는데 이 예외가 spring MVC 예외이기 때문에 빈 바디가 반환되었습니다.
- ExceptionAdvice에 MissingServletRequestPartException을 처리하는 함수를 override해주었습니다.
- 더 찾아보고 추가할 예외가 있으면 추가하겠습니다!
close: #124
> fix: 잘못된 폼 전달 시, 400 bad request 응답만 뜨고 return이 안되는 문제

- family-moments/src/main/java/com/spring/familymoments/config/advice/ExceptionAdvice.java
- 찾아보니까 해당 에러도 일반적으로 예외처리를 하고 있어 추가했습니다.
- 파일 업로드 시, 용량이 클 때 발생하는 에러 예외 처리
> feat: 파일 업로드 용량 초과 에러 예외 처리

- family-moments/src/main/java/com/spring/familymoments/domain/user/AuthController.java
- 토큰 재발급 api :
- `문제` : authcheck 어노테이션이 부재해서 해당 api에서 **불필요한 461 에러 발생**
- (해당 api에서 461 에러 불필요한 이유 : 461에러 발생 시에만 호출되는 api이기 때문)
- `해결` : authcheck 어노테이션 추가
- 로그아웃 api :
- `문제` : 오류 상황에서도 200 OK가 발생 (즉, 200 OK와 에러 상황 구별 모호)
- 200 OK
- 403 error (blacklist)
- `해결` :  status code 포함한 response body 추가 
+ 리펙토링 : auth intercepter와 중복되는 exception 제거
> Fix : 토큰 재발급 api, 로그아웃 api 버그 수정

- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/model/FamilyUpdateReq.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyReq.java
1. 가족 정보 수정 api
- 가족 이름, 가족 이미지 수정
2. 가족 생성 api noAuthCheck 제거
- 인증이 필요한 api 이므로 제거
3. 가족 생성 api consumes, produces 추가
- 스웨거 사용을 위해 추가
4. 가족 생성 시 글자수 제한 validation 추가
- 해당 validation 없이 제한을 넘은 요청이 들어오면 500 error 발생할 수 있음
> feat: 가족 정보 수정 api

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostWithUserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserService.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/model/SocialLoginSdkRequest.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- 모바일 SDK 버전 네이버/카카오 API : 
웹이 아닌 네이티브 앱에서는 프론트가 개발자 환경 세팅부터 token을 발급하는 과정 모두 진행함.
- 회원정보조회API :
글이 삭제돼도 회원정보조회API에서 글 개수가 줄어들지 않는 문제 
- 모바일 SDK 버전 네이버/카카오 API : 
우리 서비스는 자체 토큰을 발급해주기 때문에 카카오/네이버 토큰을 서버에 저장할 필요 없어짐.
해당 소셜(네이버/카카오)로 이미 가입한 회원인지의 여부만 확인해주고 
회원은 바로 로그인 시키고, 비회원은 가입하게 하면 됨.
- 회원정보조회API :
active 시 조건 추가
- 모바일 SDK 버전 네이버/카카오 API : 
- 성공
- 비회원 시 481에러 반환
> feat : 모바일 SDK 버전 네이버/카카오 API 및 리펙토링, fix : 회원정보조회API 

- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- 가족 생성일 조회 시, 부정확한 값 반납 오류 해결
- 가족 DB
- 현재 날짜를 기준으로 D+day 계산한 결과
- Postman 조회 성공
- Postman 존재하지 않는 가족 조회시
> fix: 가족 생성일 조회 시, 부정확한 값 반납 오류 해결

- family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java
> fix: 초대코드로 조회 시 familyId가 null인 문제

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentReportRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/entity/Comment.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/entity/CommentReport.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostReportRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/Post.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/PostReport.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/ReportReason.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/ContentReportReq.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java
`ERD 변경`
- 신고 사유를 저장하기 위해 **PostReport**, **CommentReport** entity를 생성했습니다.
- Comment entity에 **reported** field를 추가했습니다.
- 작업 내역 
- 신고 누적 3회 시, User, Post, Comment의 status가 INACTIVE으로 바뀝니다. 
- 게시글/댓글 신고시 정해진 string 값으로 api를 호출해야 exception을 피할 수 있습니다.
- 유저, 게시글, 댓글 inactive 시 조회 되지 않게 하는 기능이 잘 구현이 되어있는지 확인하셔야 합니다.
- 더미 데이터 사라질 예정입니다.
> feat: 유저/게시글/댓글 신고 api 구현

- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/GoogleLoginServiceImpl.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/KakaoLoginServiceImpl.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/NaverLoginServiceImpl.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserService.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/entity/SocialInfo.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/model/SocialLoginDto.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/model/SocialLoginResponse.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/model/SocialUserResponse.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/model/UserJoinRequest.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- snsId 제거 되었습니다.
- request body에서도 snsId 제거 되었습니다.
- fcmToken 소셜로그인에도 추가했습니다.
- 일반회원가입 response 형태를 string으로 (기존에 email 등등을 보냈었음)
- entity에 있는 필드인 snsId를 빼려 했지만, table을 drop 후 반영해야 해서 임시로 default 만 넣어서 해결했습니다.
- 추후 socialInfo table도 빼도 될듯합니다 ! (snsId 필드도 없앴고 해서..)
> fix : 소셜 snsId 제거, 일반 회원가입 response string으로

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/Post.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/SinglePostRes.java
- Post 정보 반환 시 본인의 게시물 여부를 반환하는 변수를 추가해달라는 요청 (**전체 22** 회의록 참고) 이 있어서 `written` 변수를 추가했습니다 🚀 
- 본인이 작성한 글이면 true, 아니면 false를 반환합니다
- 따라서 **게시글 작성 API 실행 후 `written`은 default로 true를 반환**합니다
- 게시글 수정과 삭제 API의 예외 메세지가 같아서 분리했습니다
- `createPost` 함수 리펙토링 진행 (https://github.com/familymoments/family-moments-BE/pull/140#discussion_r1555874710)
- 본인이 작성한 글이면 true, 아니면 false를 반환합니다
- **게시글 작성 API 실행 후 `written`은 default로 true를 반환**합니다
- Post 관련 API의 Response가 많이 바뀔 예정입니다 🔔
> fix: 본인의 게시물 여부를 반환하는 변수 추가

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostEmailReq.java
- `@NotBlank`를 사용하면 이메일을 보내는 시점에 이미 코드가 입력되어 있어야 하는 문제가 발생
- 본인인증 메일 발송 API에서 code의 `@NotBlank` 삭제 후 `empty`로 전환
> fix: 본인인증 메일 발송 API 수정 (@Valid 적용)

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- 유지되고 있던 PostController 내부의 BaseException try-catch을 삭제하였습니다.
- createPost 메소드에 존재했던 RuntimeException try-catch의 경우,
service에서 더이상 RuntimeException을 throw하지 않아 삭제하였습니다.
([#bb2c8b1](https://github.com/familymoments/family-moments-BE/commit/bb2c8b1169ee2f0a8fc89174ef716508599b420c) 커밋 참조)
> refactor: PostController의 불필요한 try-catch문 삭제

- family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- 회원탈퇴- 가족구성원 1명인데, 그 1명이 owner일 때 탈퇴 가능하고 가족도 삭제시킴.
- response는 동일합니다.
> fix: 회원탈퇴- 가족구성원 1명인데, 그 1명이 owner일 때 탈퇴 가능

- family-moments/src/main/java/com/spring/familymoments/domain/awsS3/AwsS3Controller.java
- family-moments/src/main/java/com/spring/familymoments/domain/awsS3/AwsS3Service.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- s3 버킷 업로드 경로 변경
- s3 버킷의 `fm-origin` 디렉토리에 업로드한 경우에만 resizing 작업이 실행됨
- 리사이징된 이미지는 `thumbnails` 디렉토리에 저장되며, DB에 저장되는 url은 썸네일을 기본으로 함
- 원본 이미지가 필요한 경우, 이미지의 url 경로에서 `thumbnails`을 `fm-origin`으로 교체
- 예시
- 썸네일 : `https://sample-bucket.com/thumbnails/filename.jpg`
- 원본 : `https://sample-bucket.com/fm-origin/filename.jpg`
- S3 API 중 Delete API의 누락된 Annotation 추가
- S3 Controller - `NoAuthCheck` 처리
- S3 Controller에서의 Token 검증이 어색한 부분이 있어 임의로 `NoAuthCheck` 처리를 해두었습니다.
최소한의 검증이 필요하다고 판단되면 롤백하겠습니다. 
- Delete API의 경우 API 매개변수에 어노테이션 처리가 되어 있지 않아 PathVariable인지, QueryString인지 파악이 불가능해 임의로 어노테이션을 붙였습니다.
- 프로필 이미지의 경우 별도의 메소드를 사용해야해서 User Domain을 수정하던 중, 수정하면 좋을 듯한 부분이 보여 같이 언급합니다.
**아래 내용과 관련해서 다들 의견 꼭 남겨주세요!** 
- User Controller에서의 DTO의 검증이 Controller에서 처리가 이루어지고 있는데, 해당 내용 `@Valid` 어노테이션으로 처리가 …
> feat: 이미지 리사이징 (썸네일 생성)

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- 게시물 수정 API 에서는 작성자의 정보로 `postLove`를 검색해도 상관이 없는 반면, 게시물 조회 API 들에서는 작성자의 정보가 아니라 로그인 유저의 정보로 `postLove`를 검색해야 한다는 부분을 놓쳐 발생한 오류였습니다! 😢  
- 작성자가 아닌 로그인 유저로 `postLove`를 검색하도록 수정했습니다!
- 이전과 같습니다. (#166)
- **2차 QA 중 '게시글 좋아요 오류' 와 관련**된 PR 입니다!
> fix: 일부 게시물 조회 API의 좋아요 정보 에러 수정

- family-moments/src/main/java/com/spring/familymoments/domain/alarmSetting/AlarmSettingRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentReportRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/entity/Comment.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/entity/CommentReport.java
- family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostReportRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/PostReport.java
- family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/SocialUserService.java
- family-moments/src/main/java/com/spring/familymoments/domain/socialInfo/entity/SocialInfo.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/AuthService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/EmailController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
1. [fix : 소셜 회원가입 수정 - ACTIVE, response, entity](https://github.com/familymoments/family-moments-BE/pull/189/commits/ac229ddbf116055b0c1c8a8ce54f91db42ab5892)
- SocialInfo entity lazy 방식으로 수정 -> (추후 리펙토링 시, snsId 불필요로 해당 테이블 삭제 예정)
- 소셜 회원가입과 일반 회원가입의 response 동일하게 수정
- 소셜 회원가입 시, active 한 유저만 이미 존재하는 유저로 필터링 
2. [fix : 회원 가입 - ACTIVE 수정](https://github.com/familymoments/family-moments-BE/commit/97255847b7733cd938fe51343d29ee2f16299940)
- 아이디 중복 확인, 이메일 중복 확인, 이름+이메일 확인 -> repository 메소드 active 추가해서 변경함. @sonshn 확인 필요
3. [fix : 회원 탈퇴 (soft delete) 및 set null 설정](https://github.com/familymoments/family-moments-BE/commit/26c05e7b993c4b68e37436349916411d84124d21)
- 기존 soft delete 방식 그대로이지만, 누락된 부분 (socialInfo, alarmSetting, ..) 추가
- fcmToken 관련 controller -> service 단으로 옮김
- set null(알수없음)을 …
> fix : 회원 탈퇴 soft delete + 로그인/회원 가입 시 active 확인

- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- 로그인한 유저의 댓글 좋아요 여부 반환
- 댓글 조회 시 `해당 댓글의 전체 좋아요 여부`를 반환하던 로직에서 `로그인한 유저의 좋아요 여부`를 반환하도록 수정
- 가족 삭제 시 해당 user - family간 `userFamily` 매핑값 INACTIVE 처리
> feat: 로그인한 유저의 댓글 좋아요 여부 반환 / 가족 삭제 시 매핑 테이블 INACTIVE

- .idea/git_toolbox_prj.xml
- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java
- family-moments/src/main/java/com/spring/familymoments/domain/family/model/GetFamilyCreatedNicknameRes.java
- family-moments/src/main/java/com/spring/familymoments/utils/CustomDateTimeUtils.java
1.  (메인)닉네임 및 가족 생성일 조회 API - d-day 대신 UTC 시간으로 반환
2. 가족원 전체 조회 - 본인 포함/미포함 옵션 추가
3. 가족 생성 - 초대코드 UUID로만 구성
4. 가족 업로드 주기 수정 - 0입력하면 null로 변환
위 기능 순서대로
1.  프론트에서 로컬 타임으로 변경하기로 해서 UTC로 반환하도록 합니다.
2. 서비스 로직에서 처리하는 코드를 DB단으로 이동했습니다.
3. 링크 형식이 사용자에게 혼란을 가져올 수 있어 변경합니다.
4. 수정 시, url에 null을 포함할 수 없어 0으로 입력받고 서버 내부에서 변경하도록 했습니다.
1.  (메인)닉네임 및 가족 생성일 조회 API - d-day 대신 UTC 시간으로 반환
2. 가족원 전체 조회 - 본인 포함/미포함 옵션 추가
3. 가족 생성 - 초대코드 UUID로만 구성
4. 가족 업로드 주기 수정 - 0입력하면 null로 변환
> fix: 가족 관련 프론트 요청 사항 수정

- family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java
- INACTIVE 처리된 family가 조회되는 오류 fix
> fix: 초대코드로 가족 리스트 조회 ACTIVE만 조회하도록 보완

- family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java
- uploadCycle이 null인 경우 0으로 반환하도록 수정
> fix: 가족 정보 조회 시, uploadCycle이 null인 경우 에러 보완

- family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentReportRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java
- family-moments/src/main/java/com/spring/familymoments/domain/comment/entity/CommentReport.java
- family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/common/entity/UserFamily.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostReportRepository.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/PostReport.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
1. hard delete
- mysql cascade 걸어둬서 유저 탈퇴 시 관련 정보 모두 삭제
=> set null fk db 변경은 배포 이후 진행 (현재는 method로 null 처리 중.)
2. Xreport 관련 테이블(CommentReport, PostReport) : offenderemail 칼럼 추가, 컨텐츠(comment/post) fk nullable = trueX
- 기존 : 탈퇴한 사용자가 신고를 했던 내역을 남기는 것
- 변경 : (원래 기획대로) 탈퇴한 사용자가 **신고 받았던 내역** 남기는 것
-> 참고할점 : 탈퇴한 사용자가 신고한 내역은 cascade 영향으로 전부 삭제될 예정. (남기는 게 의미없다고 판단했음) 
=> xxxxxxxxx (회의 통해 삭제)
3. 유저 신고
- 본인 신고 예외처리 추가
- 유저번호가 아닌 유저아이디로 신고
-> 참고할 점 : 유저 신고 3번 이상시 자동 탈퇴인데, 이 해당 유저가 가족 생성자라도 예외없이 삭제되어 가족삭제됨.(가족 내 활동 내역 전부 삭제됨)
> fix : 유저 완전 삭제, 신고 기능 수정

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/entity/Post.java
- 기존 `deletePost` 함수는 완전 삭제와 INACTIVE 처리가 혼용되어 신고 및 탈퇴 후 일부 상황에서 조회가 되지 않던 오류가 있었습니다 (@zzo3ozz)
- 신고 및 탈퇴 코드 확인 결과 INACTIVE 처리는 해당 기능을 수행하는 함수에서 처리하는 것이 맞다고 생각하여 기존 `deletePost`함수는 완전 삭제만 하도록 수정했습니다. (@spacewalk00)
- Post 엔티티의 `delete` 함수 삭제 
- 기존과 같습니다!
> fix: Post 삭제 API 수정

- family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- family-moments/src/main/java/com/spring/familymoments/domain/post/model/PostEditReq.java
- 이미지는 그대로 두고, 내용만 변경하는 경우를 고려해서 새로운 이미지를 추가하지 않고도 수정이 가능하도록 했습니다
- 의미를 명확하게 하기 위해 DTO와 Request의 `imgs` 필드명을 `newImgs`로 변경했습니다
- 이미지는 그대로 두고, 내용만 변경하는 경우를 고려해서 새로운 이미지를 추가하지 않고도 수정이 가능하도록 했습니다
- 의미를 명확하게 하기 위해 DTO와 Request의 `imgs` 필드명을 `newImgs`로 변경했습니다
- 이전과 같습니다
- 새로운 이미지를 추가하지 않고도 수정이 가능하도록 했습니다
- 이외는 #212 와 같습니다
> fix: 게시물 수정 API
