familymoments/family-moments-BE

family-moments/.gitignore, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostUserReq.java, family-moments/src/main/java/com/spring/familymoments/utils/ValidationRegex.java, family-moments/src/test/java/com/spring/familymoments/UserControllerTest.java
- [] 신규 기능 추가 :
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #2
=> chore: User birthdate localdate로 변경

.idea/FamilyMoments_Back.iml, family-moments/build.gradle, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyReq.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyRes.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java
- [] 신규 기능 추가 :
- getUser 메소드명 수정: getUser -> getUserMinjeong
close: #4 
- UserService 내의 getUser 메소드를 getUserMinjeong으로 수정했습니다.
=> fix: getUser 메소드명 수정

family-moments/build.gradle, family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/config/secret/Secret.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostUserReq.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostUserRes.java, family-moments/src/main/java/com/spring/familymoments/utils/GsonUtils.java, family-moments/src/main/java/com/spring/familymoments/utils/SHA256.java, family-moments/src/main/java/com/spring/familymoments/utils/Utils.java, family-moments/src/main/java/com/spring/familymoments/utils/UuidUtils.java, family-moments/src/main/java/com/spring/familymoments/utils/ValidationRegex.java
- 토큰 갱신 로직과 `@Notblank`는 추후에 추가하겠습니다! 😅 
- 포스트맨에서 실행하셨을 때, 가입한 회원의 이메일, 닉네임, 프로필 이미지 URL, 토큰 값이 화면에 뜨면 성공입니다.
- 자세한 것은 곧 노션에 작성하겠습니다. 😅 
- 급하시거나 궁금한 내용이 있는 분들은 언제든지 질문주세요! 😄 
- 충돌을 해결하기 위해 제 포크 저장소에서 커밋을 두 번 진행하고 한 번에 PR를 생성했습니다.
- 이미지를 업로드 해도, 안 해도 현재는 null로 반환됩니다.
- 로그인 구현 완료 후 토큰 값을 반환하는 부분은 보안 상의 이유로 **반드시** 수정할 예정입니다.
- `build.gradle`이 바뀌었으니 다시 돌려주세요!
- 최초로 풀을 받을 때 충돌이 발생했는데 `stash`를 하지 않고 제가 작업한 내용을 먼저 제 포크 저장소에 `commit`한 후, 다시 풀을 받아 충돌을 고친 후 다시 `commit`을 진행했더니 잘 진행되었습니다!
- 🔔 현재 코드에는 `Jwt` 관련 부분이 없습니다. 자세한 내용과 코드는 좀 더 정리해서 톡방에 올리도록 하겠습니다!
- 🔔 다음에 커밋하거나 PR 생성하실 때 **꼭!** `.gitignore`에 secret 폴더 경로 추가되어 있는지 확인하고 해주세요!!!
=> feat : 회원가입 api 구현

family-moments/build.gradle, family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/user/EmailController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostEmailReq.java
-  본인 인증 메일 발송 기능을 구현했습니다!
- 인증 코드를 받을 이메일을 작성하면 이메일에 인증 코드가 적힌 메일이 도착합니다!
- 인증 메일의 내용은 나중에 수정될 예정입니다.
- 🔔 `build.gradle` 다시 돌려주세요!
close: #
- 아이디 찾기 기능을 구현하다가 본인 인증 메일 발송 기능을 먼저 구현해서 올립니다!
- 비밀번호 찾기에서도 같은 기능이 활용됩니다.
- **`application.yml`에 추가 코드가 필요합니다!**
=> feat: 본인 인증 메일 발송

.idea/compiler.xml, family-moments/build.gradle, family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/awsS3/AwsS3Controller.java, family-moments/src/main/java/com/spring/familymoments/domain/awsS3/AwsS3Service.java, family-moments/src/main/java/com/spring/familymoments/domain/awsS3/entity/AwsS3.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- S3 설정, 이미지(단일, 복수) 버킷에 저장, 삭제
- ![image](https://github.com/familymoments/family-moments-BE/assets/63528205/4c656ec3-45a6-44a8-ba78-862ef9254309)
- ![image](https://github.com/familymoments/family-moments-BE/assets/63528205/d493a167-bec6-4269-af33-c1d3ac6188ca)
close: #
노션 추가설정 페이지 참고 부탁드립니다.
=> feat: S3 설정, 이미지(단일, 복수) 버킷에 저장, 삭제

family-moments/src/main/java/com/spring/familymoments/domain/user/EmailController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/GetUserIdRes.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostEmailReq.java
- `Internal~Exception` 적용: 내부 오류 발생으로 `BaseException` 대체
- 아이디 찾기 구현
- **`PostEmailReq` 수정**
- 본인 인증 메일 발송 -> 아이디 찾기 순으로 진행해야 함!
- **본인 인증 메일 발송** API에서 발송한 코드와 **아이디 찾기** API에서 입력한 코드가 서로 다르면 예외처리 되는 것 확인
close: #
=> feat: 아이디 찾기

family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- 프로필 이미지 업로드 구현
- `UserController`에서 해결 
- 반환된 이미지 URL 값을 주소창에 복붙했을 때 사진 원본이 뜨면 성공! 
- 다른 쪽에서 필요할 것 같아서 급하게 프로필 사진 업로드 부분만 추가했습니다.
- 예외처리 완료는 토요일까지 완료하겠습니다.
close: #
=> fix: 회원가입 프로필 사진 업로드 추가

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentWithUserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/entity/Comment.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/PostCommentReq.java, family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/GetFamilyAllRes.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/GetFamilyCreatedNicknameRes.java, family-moments/src/main/java/com/spring/familymoments/domain/post/PostWithUserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/post/entity/Post.java
- 가족 및 댓글 관련 api 개발 완료했습니다.
- 닉네임 및 가족 생성일 조회
- 가족원 전체 조회
- 가족 삭제
- 가족 업로드 주기 수정
- 댓글 생성
- 기타 에러 메시지 수정
-![image](https://github.com/familymoments/family-moments-BE/assets/63528205/b2a905eb-3330-4558-9ed0-fe0cbbde4798)
close: #
=> feat: 가족 및 댓글 API 생성

family-moments/src/main/java/com/spring/familymoments/domain/post/PostWithUserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
1. 프로필 조회 시 totalUpload의 의미가 <모든 가족에서 내가 작성한 게시물의 수> -> <현재 가족 기준 내가 작성한 게시물의 수>로 확정되면서, url에 pathvariable로 familyId를 추가하여 관련 코드들을 수정했습니다.
2. 유저 검색 시 parameter로 된 familyId를 pathvariable로 변경했습니다.
- 특이 사항
close: #15 #18
=> Feature/profile + Feature/user-search

family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- 기존: users/profile/families/{} -> 변경후: users/families/{}/profile
close: #31
=> chore : profile api url 변경

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/user/EmailController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- 가능한 선에서 예외 처리할 때 `Internal~` 를 `BaseResponse<T>`로 대체하였습니다.
- **이유**: 좀 더 명확하게 오류를 정의할 필요가 있다고 생각했습니다.
- 가능한 선에서 예외 처리할 때 `Internal~` 를 `BaseResponse<T>`로 대체하였습니다.
- 이메일 관련 로직에서 유효성 검사 예외 처리를 놓친 부분이 많아 추가하였습니다.
- 명세서에 작성하겠습니다.
close: #
=> refactor: 예외 처리 (Internal -> BaseResponse)

family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentWithUserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/GetCommentsRes.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
=> feat: 특정 게시물의 댓글 목록 조회 API - 미완성

family-moments/src/main/java/com/spring/familymoments/domain/user/entity/User.java
- 이유: 서버에서 로그인할 때 `403`에러 반복 발생
- user entity의 일부 method 수정
close: #
=> fix: user entity 수정

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentWithUserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/GetCommentsRes.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- 특정 게시물의 댓글 목록 조회 API
- 댓글 삭제 API
- ![image](https://github.com/familymoments/family-moments-BE/assets/63528205/8b58f387-ee78-43c3-be0b-1a23e5e59d6e)
=> feat: Comment - 특정 게시물의 댓글 목록 조회 API, 댓글 삭제 API

family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
UserFamily inviteCode 추가
- UserFamily inviteCode 추가
=> fix: Family - 가족 생성 API

family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> 2차 배포 - userFamily 이슈 해결

family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java, family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java
- post Create 시 에러 처리 추가
post create 시, 존재하지 않는 familyId가 확인되는 경우의 exception case를 추가하였습니다.
- 앨범을 위한 api를 추가하였습니다.
=> feat: Album 기능 추가

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/user/AuthController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/AuthService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
close: #11 
- 회의 시간에 말한 예외 처리 부분 수정했습니다.
=> fix : access token 예외처리

family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- 초대 리스트 확인, 게시글 좋아요 `Controller`에 access token 예외 처리 추가
- 초대 리스트 확인, 게시글 좋아요 `Controller`에 access token 예외 처리 추가
- 명세서에 작성했습니다.
close: #
=> fix: access token 예외 처리

family-moments/src/main/java/com/spring/familymoments/domain/user/EmailController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java
- 본인 인증 메일의 디자인 변경
- 본인 인증 메일의 디자인 변경
- 기능은 #14 와 같습니다!
close: #
=> fix: 본인 인증 메일 발송

family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> fix: Family, Comment Redis를 이용한 유효 사용자 인증 및 인가

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/user/AuthController.java
- accessToken이 만료되었을 때: 401 error code  -> **461 error code**
- refreshToken이 만료되었을 때: 401 error code -> **471 error code** 
close: #61 
에러 코드 변경했습니다
=> fix : Token 만료 에러코드 번호 변경

family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java
- 가족 수정 api에 포함되어 있던 가족 권한 넘기기 기능을 따로 구현했습니다.
=> Family authority

family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyRes.java
inviteCode 추가
- 프론트 요청으로 가족 생성 반환값에 inviteCode 추가했습니다.
- PostFamilyRes DTO 변경
- ![image](https://github.com/familymoments/family-moments-BE/assets/63528205/dec4176a-9960-48a0-8457-902f2329ab3b)
=> fix: Family - 가족 생성 반환값 변경

family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/FamilyIdDto.java
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> feat: 가족 초대코드로 가족 가입

family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
- `CommentService`에 Transactional 수정 및 추가
- `CommentService`에 Transactional 수정 및 추가
- 동작 
- `CommentService`에 Transactional 수정 및 추가
close: #
=> feat: CommentService에 Transactional 수정 및 추가

family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserService.java
=> release : 0.4.2

family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/GetCommentsRes.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java
- 프론트 요청
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> fix : commentList 반환 시 postId 정보 추가 리턴

family-moments/src/main/java/com/spring/familymoments/config/BaseException.java, family-moments/src/main/java/com/spring/familymoments/config/NoAuthCheck.java, family-moments/src/main/java/com/spring/familymoments/config/advice/ExceptionAdvice.java
- controller에서 반복적으로 처리하던 인증 관련 코드 한번에 처리 가능
- controller에서 처리하던 BaseException 한번에 처리 가능 
- controller에서 필요한 로직에만 집중할 수 있음
- AuthIntercepter 추가
- NoAuthCheck 추가
- ExceptionAdvice에 BaseException 처리 코드 추가
=> Auth intercepter

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- authintercepter와 exception 처리를 반영한 리펙토링
- 가족 정보 조회 api 리팩토링
=> refactor: 가족 정보 조회 api 리팩토링

family-moments/build.gradle, family-moments/src/main/java/com/spring/familymoments/config/advice/ExceptionAdvice.java, family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/FamilyUpdateDto.java
=> refactor: Family refactor

family-moments/build.gradle
=> chore: build.gradle 버전 컨트롤

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/FamilyRes.java
transaction readOnly 설정 안 하신 분들 하시면 좋을 것 같습니다!
참고) transaction readOnly 설정해야 하는 이유
https://miniature-tsunami-9f2.notion.site/Transactional-readOnly-true-e4fe4ad121424f7a8dc5516724cc74ea?pvs=4
=> Family refactor

.idea/compiler.xml, family-moments/build.gradle, family-moments/src/main/java/com/spring/familymoments/domain/awsS3/AwsS3Controller.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/GetCommentsRes.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/PostCommentReq.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/GetFamilyAllRes.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/GetFamilyCreatedNicknameRes.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyReq.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyRes.java
- swagger 적용
- 기존 controller의 user validation 삭제
=> refactor: family, comment 도메인 리팩토링 및 swagger 적용

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/user/AuthService.java
가족 아이디가 없으면 발생하는 exception으로 인해 이후 진행되어야 하는 토큰 갱신이 누락되었습니다. 😄
=> fix : 소속된 가족이 없는 회원에게 토큰 발급

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/config/MultipartJackson2HttpMessageConverter.java, family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/MyFamilyRes.java, family-moments/src/main/java/com/spring/familymoments/domain/user/UserController.java
- 가족 다중 추가 
- 내 가족 리스트 조회 api
- 가족 초대 api - 다른 가족에 가입한 경우에도 초대할 수 있도록 수정
- 가족 생성 api - 5개의 가족에 가입한 경우, 생성 불가능
- 내 초대 리스트 api - status가 DEACCEPT인 경우만 반환하도록 수정
- 가족 가입 api - 55개의 가족에 가입한 경우, 가입 불가능
- swagger에서 @RequestPart,MultipartFile로 요청을 보내면 content type 오류가 발생해 이를 해결하기 위해 MultipartJackson2HttpMessageConverter 파일을 추가하였습니다.
- 참고) https://velog.io/@zvyg1023/Spring-Boot-Swagger%EC%97%90%EC%84%9C-ReqeustPart%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-MultiPartFile%EA%B3%BC-DTO-%EC%B2%98%EB%A6%AC-%EC%8B%9C-Content-type-applicationoctet-stream-not-supported-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0
=> feat: 가족 다중 추가

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentService.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/entity/Comment.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/PatchCommentReq.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- 작업 내역 
- 댓글 수정 api 호출 전
- 댓글 수정 api 호출
- 댓글 수정 api 호출 후 DB
- 댓글 내용을 입력하지 않은 경우
=> feat: 댓글 수정 api

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- 메인 화면의 상단 바에 사용될 가족 이름만 조회하는 API입니다.
**1. 사용될 UI 화면**
**2. 정상 응답**
**3. 비정상 응답**
- 존재하지 않는 가족 or 삭제된 가족일 경우
- 유저가 조회하려는 가족에 속해있지 않았을 경우
=> feat: 가족 이름 조회 API

.idea/deployment.xml, .idea/sshConfigs.xml, .idea/webServers.xml, family-moments/src/main/java/com/spring/familymoments/domain/alarmSetting/AlarmSettingController.java, family-moments/src/main/java/com/spring/familymoments/domain/fcm/FCMController.java, family-moments/src/main/java/com/spring/familymoments/domain/fcm/FCMScheduler.java
- 안드로이드 측 알림 개발 시, 테스트해볼 수 있도록 스케줄링이 아닌 api 요청으로 알림이 구동될 수 있도록 api를 추가했습니다.
=> feat: [개발용]업로드 알림 전송 api 추가

family-moments/src/main/java/com/spring/familymoments/domain/family/entity/Family.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/FamilyRes.java
=> fix: 가족 정보 조회 시, 가족 대표의 userId를 반환하도록 수정

family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/PatchCommentReq.java, family-moments/src/main/java/com/spring/familymoments/domain/comment/model/PostCommentReq.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/PostFamilyReq.java
- 기존에 java 코드로 null 체크했던 부분을 @NotBlank을 사용하는 방법으로 변경했습니다.
=> feature: @NotBlank 추가, try-catch 제거

family-moments/src/main/java/com/spring/familymoments/domain/common/entity/UserFamily.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/family/model/FamilyAuthorityReq.java
=> feat: 가족 초대 거절 API, 가족 권한 확인 API

family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostLoginReq.java
=> fix: 가족 가입 api 복구

family-moments/src/main/java/com/spring/familymoments/domain/post/PostRepository.java
- 무한 스크롤 문제가 발생하여 페이징 조건을 수정하였습니다!
- 앨범 API - 페이징 조건 수정
- 이전과 같습니다! (#140)
- **2차 QA와 관련**된 PR 입니다!
=> fix: 앨범 API 수정

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/commentLove/CommentLoveService.java, family-moments/src/main/java/com/spring/familymoments/domain/commentLove/CommentLoveWithUserRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java, family-moments/src/main/java/com/spring/familymoments/domain/post/entity/Post.java, family-moments/src/main/java/com/spring/familymoments/domain/postLove/PostLoveService.java
- family 도메인 코드 정리
- BaseResponseStatus 도메인 별로 정리
- comment love 코드 정리
=> Feature/refactor: family, comment 도메인 코드 정리

family-moments/src/main/java/com/spring/familymoments/config/BaseResponseStatus.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
- 가족 권한자만 가족 수정 가능 하도록 보완
- 가족 강퇴, 권한 넘기기 본인 예외 처리 보완
=> refactor: 가족 api 예외처리 보완

family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java
=> chore: #194 PR의 누락된 파일

family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
=> fix: 가족원 조회 api 본인 제외하도록 수정

family-moments/src/main/java/com/spring/familymoments/domain/common/UserFamilyRepository.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyController.java, family-moments/src/main/java/com/spring/familymoments/domain/family/FamilyService.java
=> release: 0.11.4

family-moments/src/main/java/com/spring/familymoments/domain/user/EmailController.java, family-moments/src/main/java/com/spring/familymoments/domain/user/EmailService.java, family-moments/src/main/java/com/spring/familymoments/domain/user/model/PostEmailReq.java
- 기존 PR를 합치기 위해 충돌을 Resolve 하다가 잘못 고친 부분이 있는 것을 확인하여 급하게 수정하였습니다
=> fix: EmailService 충돌 해결

family-moments/src/main/java/com/spring/familymoments/domain/post/PostController.java, family-moments/src/main/java/com/spring/familymoments/domain/post/PostService.java, family-moments/src/main/java/com/spring/familymoments/domain/post/model/PostEditReq.java, family-moments/src/main/java/com/spring/familymoments/domain/post/model/SinglePostRes.java
- 이미지는 그대로 두고, 내용만 변경하는 경우를 고려해서 새로운 이미지를 추가하지 않고도 수정이 가능하도록 했습니다
- 이미지의 개수 관련 예외 처리를 수정했습니다
- 의미를 명확하게 하기 위해 DTO와 Request의 `imgs` 필드명을 `newImgs`로 변경했습니다
=> release: 0.12.3
